apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fsl-app
  namespace: production
spec:
  serviceName: "fsl-service"
  replicas: 3
  selector:
    matchLabels:
      app: fsl-app
  template:
    metadata:
      labels:
        app: fsl-app
    spec:
      containers:
        - name: fsl-container
          image: fsl-app:latest          # ✅ Local image name (no prefix)
          imagePullPolicy: Never         # ✅ Use local image only
          ports:
            - containerPort: 8080
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MY_SECRET

