name: CI - PR checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier (format)
        run: npm run prettier -- --write

      - name: Run tests
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

